# Change these first
owner: paradigmasolutions # Your GitHub organization or username, where this repository lives
repo: cgr-website-uptime # The name of this repository

sites:
  - name: CGR
    url: https://www.contraloria.gov.co

status-website:
  baseUrl: /cgr-website-uptime # where "repo" is your repository name
  name: Your Status Website

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
